#!/bin/bash
#Fixes the problem with saving in nano for example
/android/android-sdk-linux_x86/platform-tools/adb shell telnetd &
#/android/android-sdk-linux_x86/platform-tools/adb forward tcp:9999 tcp:23
/android/android-sdk-linux_x86/platform-tools/adb forward tcp:9998 tcp:22
#telnet localhost 9999

