#!/bin/bash
# Löser troligtvis några problem, ställer säkerligen till fler Sub-process /usr/bin/dpkg returned an error code (1)
cd /var/cache/apt/archives
rm irqbalance* avahi* cups* libnss-mdns* lubuntu-desktop*
cd /var/lib/dpkg/info/
rm irqbalance* avahi* cups* libnss-mdns* lubuntu-desktop*
